use crate::cell::Cell;
use super::Board;

pub fn generate(board: &mut Board, position: (usize, usize)) {
    let (column, row) = position;
    board.set_cell(row, column + 24, Cell::Alive);
    board.set_cell(row + 1, column + 22, Cell::Alive);
    board.set_cell(row + 1, column + 24, Cell::Alive);
    board.set_cell(row + 2, column + 12, Cell::Alive);
    board.set_cell(row + 2, column + 13, Cell::Alive);
    board.set_cell(row + 2, column + 20, Cell::Alive);
    board.set_cell(row + 2, column + 21, Cell::Alive);
    board.set_cell(row + 2, column + 34, Cell::Alive);
    board.set_cell(row + 2, column + 35, Cell::Alive);
    board.set_cell(row + 3, column + 11, Cell::Alive);
    board.set_cell(row + 3, column + 15, Cell::Alive);
    board.set_cell(row + 3, column + 20, Cell::Alive);
    board.set_cell(row + 3, column + 21, Cell::Alive);
    board.set_cell(row + 3, column + 34, Cell::Alive);
    board.set_cell(row + 3, column + 35, Cell::Alive);
    board.set_cell(row + 4, column, Cell::Alive);
    board.set_cell(row + 4, column + 1, Cell::Alive);
    board.set_cell(row + 4, column + 10, Cell::Alive);
    board.set_cell(row + 4, column + 16, Cell::Alive);
    board.set_cell(row + 4, column + 20, Cell::Alive);
    board.set_cell(row + 4, column + 21, Cell::Alive);
    board.set_cell(row + 5, column, Cell::Alive);
    board.set_cell(row + 5, column + 1, Cell::Alive);
    board.set_cell(row + 5, column + 10, Cell::Alive);
    board.set_cell(row + 5, column + 14, Cell::Alive);
    board.set_cell(row + 5, column + 16, Cell::Alive);
    board.set_cell(row + 5, column + 17, Cell::Alive);
    board.set_cell(row + 5, column + 22, Cell::Alive);
    board.set_cell(row + 5, column + 24, Cell::Alive);
    board.set_cell(row + 6, column + 10, Cell::Alive);
    board.set_cell(row + 6, column + 16, Cell::Alive);
    board.set_cell(row + 6, column + 24, Cell::Alive);
    board.set_cell(row + 7, column + 11, Cell::Alive);
    board.set_cell(row + 7, column + 15, Cell::Alive);
    board.set_cell(row + 8, column + 12, Cell::Alive);
    board.set_cell(row + 8, column + 13, Cell::Alive);
}
